project_id = "ccwbdarlfwmqbeftppzk"

[functions.send-welcome-email]
verify_jwt = false

[functions.rebel-ai-chat]
verify_jwt = false

[functions.gumroad-verify-license]
verify_jwt = false

[functions.gumroad-webhook]
verify_jwt = false

[functions.generate-social-image]
verify_jwt = false
